# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='youtube_id',
        ),
    ]
