# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170626_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='q',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
